# Generated by Django 6.0.6 on 2026-06-04 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkam', '0002_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
