# Generated by Django 6.0.5 on 2026-06-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkam', '0005_transactions_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='limit',
            field=models.FloatField(max_length=10),
        ),
    ]
