# Generated by Django 6.0.5 on 2026-06-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkam', '0007_budget_category_replace_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='limit',
            field=models.FloatField(),
        ),
    ]
